config/routes.rb
Rails.application.routes.draw do

  

  resources :tweets, only: [:index, :new, :create, :edit, :update, :destroy] do
    collection do
      post :confirm
    end
  end
  
  root 'top#index'
  

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  validates :title, :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  before_action :set_tweet, only: [:edit, :update, :destroy]
  
  def index
    @tweets = Tweet.all
  end

  def new
    if params[:back]
      @tweet = Tweet.new(tweets_params)
    else
      @tweet = Tweet.new
    end
  end

  def create
    @tweet = Tweet.create(tweets_params)
    if @tweet.save
        redirect_to tweets_path, notice: "つぃーとを投稿しました！"
    else
      render 'new'
    end
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def update
    @tweet = Tweet.find(params[:id])
    @tweet.update(tweets_params)
    redirect_to tweets_path, notice: "つぃーとを更新しました！"
  end
  
  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet.destroy
    redirect_to tweets_path, notice: "つぃーとを削除しました！"
  end

  def confirm
    @tweet = Tweet.new(tweets_params)
    render :new if @tweet.invalid?
  end

  private
    def tweets_params
      params.require(:tweet).permit(:title, :content)
    end
  
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
      def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_tweets_path
    elsif action_name == 'edit'
      tweet_path
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  
  <title>Tweets</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <header>
    
    <ul>
      <li><%= link_to "トップページ", root_path %></li>
      <li><%= link_to "つぃーと", tweets_path %></li>
    </ul>
  </header>

<%= yield %>

</body>
</html>

app/views/top/index.html.erb
<section class="main-header">
  <img src="<%= asset_path "mzl_krmtcmyd.png" %>">

  <h1>つぃーと</h1>
</section>
<div id="page-top-btn" class="page-top-btn">
    <p><a class="move-page-top" id="move-page-top">▲</a></p>
</div>

app/views/tweets/_form.html.erb
<%= form_for(@tweet, url: choose_new_or_edit) do |f| %>
  <% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= @tweet.errors.count %>件のエラーがあります。</h2>

      <ul>
      <% @tweet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :title %>
  <%= f.text_field :title, class: 'form-control' %>
  <br>
  <%= f.label :content %>
  <%= f.text_field :content, class: 'form-control' %>
  <br>
  <%= f.submit %>
<% end %>

<%= link_to "つぃーと一覧画面にもどる", tweets_path %>

app/views/tweets/confirm.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">

<h3>以下の内容で送信する。</h3>

<%= form_for(@tweet) do |f| %>
  <%= f.hidden_field :title %>
  <%= f.hidden_field :content %>

  <p>タイトル:<%= @tweet.title %></p>
  <p>本文:<%= @tweet.content %></p>
  <%= f.submit "登録する",class: 'btn btn-primary btn-block' %>
<% end %>

<%= form_for(@tweet, url: new_tweet_path, method: 'get') do |f| %>
  <%= f.hidden_field :title %>
  <%= f.hidden_field :content %>
  <%= f.submit "もどる", name: 'back', class: 'btn btn-default btn-block' %>
<% end %>
  </div>
</div>

app/views/tweets/edit.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
　　<h2>つぃーとを編集する</h2>
　　<%= render 'form' %>
  </div>
</div>

app/views/tweets/index.html.erb
<div class="container">
  <div class="wrapper col-md-8 col-md-offset-2 col-sm-10">

<p><%= notice %></p>

<h1>つぃーと一覧</h1>

      <%= link_to "つぃーとする", new_tweet_path, class: 'btn btn-default' %>

<% @tweets.each do |tweet| %>
  <div class="row">
  <h4><strong><%= tweet.title %></strong></h4>
  <p><%= tweet.content %></p>
  <%= link_to "編集", edit_tweet_path(tweet.id), class: 'btn btn-default btn-sm btn-success' %>
  <%= link_to "削除", tweet_path(tweet.id), method: :delete, data: { confirm: '本当に削除していいですか？'}, class: 'btn btn-default btn-sm btn btn-danger' %>
    </div>
    <% end %>
  </div>
</div>

app/views/tweets/new.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
　　<h2>つぃーとする</h2>
　　<%= render 'form' %>
  </div>
</div>